#环境加载配置
spring:
  #启动环境
  profiles:
    active: dev
  #国际化文件
  messages:
    basename: i18n/messages
  #jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #文件上传限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  redis:
    #主机地址
    host: 127.0.0.1
    #端口
    port: 6379
    #密码
    password: 123456
    #超时时间，单位毫秒
    timeout: 5000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 开发环境配置
server:
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 300
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
captcha:
  #谷歌验证码类型：math/char
  captchaType: math

file:
  allowType: jpg|jpeg|png|gif|svg|ico|bmp

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: top.maplefix.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  #configLocation: classpath:mapper/mybatis-config.xml
  #configLocation和configuration不能同时出现
  configuration:
    #全局映射器启用缓存
    cache-enabled: true
    #驼峰式命名
    map-underscore-to-camel-case: true
    #sql执行器,可选SIMPLE、REUSE、BATCH
    #SIMPLE是默认执行器，根据对应的sql直接执行，不会做一些额外的操作。
    #REUSE是可重用执行器，重用对象是Statement（即该执行器会缓存同一个sql的Statement，省去Statement的重新创建，优化性能）（即会重用预处理语句）
    #BATCH执行器会重用预处理语句，并执行批量更新。
    default-executor-type: reuse
    #指定mybatis具体日志实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# PageHelper分页插件
pagehelper:
  auto-dialect: true
  #指定数据库，不指定的话会默认自动检测数据库类型
  helper-dialect: mysql
  #是否启用分页合理化。如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
  reasonable: true
  #默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  params: count=countSql

# 七牛云配置
# bucket是创建的存储空间名, [华东z0] [华东z1] [华南z2] [北美na0] [东南亚as0]
# path对应存储空间的访问域名
qiniu:
  accessKey: cp-3jdetLlkmHv0VHMfu4IQkRGEF2yqdnuoZUM9R
  secretKey: JdQ5UJA665Zsx1vzb5yjRTKhXse-v7-2bmzHOB1I
  bucket: maple_bucket
  path: http://pvwrkn8fo.bkt.clouddn.com